# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Run API tests (headless)
        env:
          BASE_URL: https://petstore.swagger.io/v2
          # API key is set on repository
          API_KEY: ${{ secrets.API_KEY }}
        run: npm test
